name: dart_web
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  convert: '>=1.0.0'
  crypto: '>=2.0.0'
  encrypt: '>=4.0.0'
  http: '>=0.13.3'
  logger: '>=1.0.0'
  tuple: '>=1.0.0'
  uuid: '>=2.0.0'
  web_socket_channel: '>=1.0.0'

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
